import { useEffect, useRef } from 'react';
import {
  isSupabaseConfigured,
  loadJobs, subscribeToJobs,
  loadScheduledSlots, subscribeToScheduledSlots,
  saveJob, deleteJob,
  appendConflictLog,
} from '../utils/supabase.js';
import { expandAutoSplits } from '../data/joinJobs.js';
import { deriveJobStatusFlags, blockedPile } from '../data/jobs.js';
import { jobAgeDays } from '../utils/jobAge.js';

// Detect top-level jobs that disappeared from the jobs table
// (e.g., CSV sync removed them without marking done in-app)
//
// `incomingJobs` here is the ALREADY-normalized/expanded array, so it is in
// app (camelCase) shape. Derived auto-split cards are excluded on both sides:
// they aren't real rows, they're regenerated every load, and a parent whose
// desc changed so it no longer auto-splits would otherwise report its old
// bench cards as vanished revenue.
// `departedJobNumbers` is the set of job numbers whose ROW still exists but
// carries departed_at — read from the raw database rows, before the filter
// below removes them from the normalized list.
//
// Without it, this detector cannot tell the two apart, because both look
// identical from the normalized side: the job is simply not there any more.
// They are not the same event at all.
//   - A row that has VANISHED from the jobs table is CSV drift: work that may
//     have been done and never invoiced. That still gets reported, exactly as
//     it always has — this is the £-on-the-floor alarm and it stays armed.
//   - A row still present and marked departed is a DELIBERATE departure: the
//     job came off the printout because Multitrack finished or invoiced it,
//     Trevor approved the list on the import preview, and the row is intact.
//     Queuing that for a "did this get invoiced?" review would have raised 16
//     false prompts on the very import meant to fix the board.
// Exported for tests only. The distinction it draws — deliberate departure vs
// genuine CSV drift — is invisible from the outside (both look like "the job is
// not there any more"), and getting it wrong is either 16 false invoicing
// prompts or a silently unreported piece of unpaid work. Worth pinning down.
export function detectDisappearedJobs(prevJobs, incomingJobs, departedJobNumbers = new Set()) {
  const incomingJobNumbers = new Set(
    incomingJobs.filter(j => !j.parentId && !j.isDerived).map(j => j.job)
  );
  return prevJobs.filter(j =>
    !j.parentId && !j.isDerived && !j.done && j.job != null &&
    !incomingJobNumbers.has(j.job) &&
    !departedJobNumbers.has(j.job)
  );
}

// Job numbers of rows that are present in the jobs table but departed. Read
// from the RAW database rows — by the time normalizeJobsFromDb() has run, these
// rows are gone from the array and the information no longer exists.
export function departedJobNumbersFromDb(dbJobs = []) {
  return new Set(
    dbJobs.filter(j => j.departed_at).map(j => j.job)
  );
}

// Transform Supabase jobs (snake_case) back to app format (camelCase), then
// regenerate the derived auto-split bench cards. That regeneration step is
// not optional bookkeeping: auto-split cards are derived-not-stored by
// design, so without it big jobs simply never break into bench cards.
export function normalizeJobsFromDb(dbJobs, benchHours = {}) {
  // The single read-side choke point for departures. A job Multitrack has
  // dropped off the printout keeps its row — tag, action, hours, bench, pomo
  // log, everything — but stops existing as far as every screen in the app is
  // concerned: Jobs Sheet, Sidebar, Jobs page, Projects page all read the array
  // this function returns.
  //
  // Filtering here rather than per-screen is deliberate and load-bearing. It
  // also removes the four orphaned auto-split bench cards for free: those are
  // derived, never stored, and regenerated by expandAutoSplits() below from
  // whatever parents survive this filter. Once the parent is gone they simply
  // stop being generated — there is nothing to delete.
  const live = dbJobs.filter(j => !j.departed_at);

  const mapped = live.map(j => {
    const backlog = j.bl === 'Y' || j.bl === true;
    const statusFlags = deriveJobStatusFlags(j.status, j.action, backlog);
    // The old status-flag rule (above) doesn't know about blockedPile(), the
    // newer rule that puts INC-action and waiting/on-hold jobs in the
    // blocked pile with no bench. Without this, a job like 393/693 (INC)
    // could read schedulable here while blockedPile() treats it as blocked
    // everywhere else, so the two screens disagree. Fold blockedPile() in so
    // ACTIVE/BACKLOG bucketing agrees with the bench-less-job rule.
    const isBlocked = blockedPile({ status: j.status, action: j.action, backlog }) != null;

    return {
      id: j.id,
      parentId: j.parent_id || null,
      job: j.job,
      customer: j.customer,
      mfr: j.mfr,
      model: j.model,
      status: j.status,
      bench: j.bench,
      // Coerced: a NUMERIC column can come back as a string over PostgREST,
      // and every split calculation in createSubtasks() is arithmetic — a
      // string here turns the derived cards' hours into NaN.
      hours: j.hours == null ? j.hours : Number(j.hours),
      // The date the job came in the door, exactly as Multitrack printed it.
      // Written only by the Jobs-by-Age import; nothing else reads it except
      // the age calculation on the next line.
      firstSeen: j.first_seen || null,
      // Job age, computed here and ONLY here — Brief G, Build 1c.
      //
      // `job.days` is read in several places across the app and two of them are
      // sort orders rather than displays (JobShelf.jsx, DailyLogPage.jsx).
      // Working the age out at each display instead would leave the cards
      // ticking correctly while the lists stayed sorted on stale stored
      // numbers. Doing it once, here, means every one of those readers keeps
      // reading the same `job.days` it always has and not one of them had to
      // change.
      //
      // The raw `j.days` COLUMN is deliberately not read — Brief H, Build 2b
      // removed the stored-days fallback, and this was the only place in the
      // app that ever read the column off a database row. The column still
      // exists and still holds stale values; ignoring it is the point.
      //
      // `null` still stays `null`: an unknown age must not read back as 0, or a
      // brand-new job and a job of unknown age become indistinguishable again.
      // `|| null` would be wrong here — it would turn a genuine 0-day job into
      // "unknown".
      days: jobAgeDays(j.first_seen),
      scheduled: j.scheduled,
      calendarSlot: j.calendar_slot || null,
      gcalEventId: j.gcal_event_id || null,
      desc: j.desc,
      tag: j.tag,
      action: j.action,
      // Lowercase to match the shape src/data/jobs.js has always produced
      // (job.vb/job.backlog/job.project) — the uppercase VB/BL/PJ here was
      // dead weight nothing downstream ever read.
      vb: j.vb === 'Y' || j.vb === true,
      backlog,
      project: j.pj === 'Y' || j.pj === true,
      ...statusFlags,
      schedulable: statusFlags.schedulable && !isBlocked,
      hasSubtasks: j.has_subtasks,
      subtasks: j.subtasks || [],
      isSplit: j.is_split,
      noAutoSplit: j.no_auto_split,
      isSubtask: j.is_subtask,
      isDerived: j.is_derived || false,
      sessionNote: j.session_note,
      sessionIndex: j.session_index,
      sessionTotal: j.session_total,
      pieceDone: j.piece_done,
      done: j.done,
      gcalEventIds: j.gcal_event_ids || [],
      pomoLog: j.pomo_log || [],
      bumpHistory: j.bump_history || [],
      created_at: j.created_at,
      updated_at: j.updated_at,
    };
  });

  return expandAutoSplits(mapped, benchHours);
}

// NOTE: slot normalization lives in loadScheduledSlots() in utils/supabase.js,
// which returns the map already shaped as slotKey -> jobId. A duplicate
// normalizer used to sit here building objects instead; it was dead code and
// the wrong shape, so it was removed rather than left as a trap.

export function useSupabase({
  jobs,
  scheduledSlots,
  setJobs,
  setScheduledSlots,
  setFirebaseReady,
  setLastSyncedAt,
  setCompletedJobs,
  setDoneJobIds,
  justSavedAt,
  firebaseReady,
  onJobsDisappeared,
  onSplitOrphansFound,
  benchHours,
  // False until the shared settings have been read (or have failed and fallen
  // back to defaults). Nothing below loads or subscribes until it is true —
  // see the init effect. Defaults to true so a caller that does not pass it
  // behaves exactly as before.
  settingsReady = true,
}) {
  const prevJoinedJobsRef = useRef([]);
  const hasSeenFirstSnapshotRef = useRef(false);

  // The init useEffect below has `[]` deps, so the realtime subscription
  // callback closes over whatever benchHours was on FIRST render and keeps it
  // for the life of the component. That first value is correct (the effect no
  // longer runs until settingsReady is true, so the real bench hours are in
  // hand before anything is normalized), but it goes stale the moment
  // the tech changes bench hours in Settings: every subsequent realtime update
  // would regenerate the bench cards with the old hours, permanently. A ref
  // kept current on every render is read instead of the captured value.
  const benchHoursRef = useRef(benchHours);
  benchHoursRef.current = benchHours;

  // Load and normalize jobs from Supabase
  async function loadAndSetJobs() {
    const dbJobs = await loadJobs();
    const normalized = normalizeJobsFromDb(dbJobs, benchHoursRef.current);

    setJobs(normalized);
    prevJoinedJobsRef.current = normalized;
    setLastSyncedAt(new Date().toISOString());

    return normalized;
  }

  // Load and normalize scheduled slots
  async function loadAndSetSlots() {
    const dbSlots = await loadScheduledSlots();
    setScheduledSlots(dbSlots);
    return dbSlots;
  }

  // Initialize on mount
  useEffect(() => {
    if (!isSupabaseConfigured()) return;
    // Wait for bench hours. normalizeJobsFromDb() -> expandAutoSplits() sizes
    // every auto-split bench card from benchHours, and that sizing is done once
    // per load — running it against an empty placeholder would leave every split
    // card on the board the wrong length until the next reload, on every load.
    // settingsReady only ever goes false -> true, so this effect still runs its
    // body exactly once and still subscribes exactly once.
    if (!settingsReady) return;

    (async () => {
      await loadAndSetJobs();
      await loadAndSetSlots();
      setFirebaseReady(true);
    })();

    // Subscribe to jobs changes
    const unsubJobs = subscribeToJobs(async (updated) => {
      // Suppress echo if we just saved
      if (Date.now() - justSavedAt.current < 5000) return;

      const normalized = normalizeJobsFromDb(updated, benchHoursRef.current);

      // Detect disappeared jobs
      if (hasSeenFirstSnapshotRef.current) {
        const disappeared = detectDisappearedJobs(
          prevJoinedJobsRef.current,
          normalized,
          // Computed from the RAW rows, which still carry departed_at —
          // `normalized` no longer does, because the filter has already run.
          departedJobNumbersFromDb(updated),
        );
        if (disappeared.length > 0) onJobsDisappeared?.(disappeared);
      } else {
        hasSeenFirstSnapshotRef.current = true;
      }

      setJobs(normalized);
      prevJoinedJobsRef.current = normalized;
      setLastSyncedAt(new Date().toISOString());
    });

    // Subscribe to slots changes
    const unsubSlots = subscribeToScheduledSlots(setScheduledSlots);

    return () => {
      unsubJobs?.();
      unsubSlots?.();
    };
  }, [settingsReady]); // eslint-disable-line react-hooks/exhaustive-deps

  // Expose methods matching useFirebase.js interface
  return {
    loadJobs: loadAndSetJobs,
    loadScheduledSlots: loadAndSetSlots,
    saveJob,
    deleteJob,
    appendConflictLog,
  };
}
